### ISSUE TITLE
Organization: team listing and team member management pages

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#222]
Parent issue is:

- #208

This issue will deal specifically with the team and team member pages. I've had a few patterns to work through on these views. This will be a little bit of a collection of a few smaller issues as I work in features from the old templates, including adapting some of the SSO rules that make these pages noop views for the user.

### Tasks

- [x] Add filter or mock filter to the team detail view, listing team members. This should show why team we're looking at currently
- [ ] #227
- [x] Add dropdown for team project list
- [x] Add multiple select field for team project form
- [x] Add template for team member add form
- [x] Add template for team project add form
- [x] Ensure that `organization.teams.all` is correct method to use on team_detail template/team member listing partial
- [x] Add member listing templates for `/members/` or `organization/member_list.html`
- [x] Add filter for teams, so we can link to the members page, filtered
- [x] Teams detail view needs to have some content? Or is this view redundant now?
- [x] Add member tab on organization base template
- [x] Add danger zone for delete button on team edit view
- [x] Combine member list and team member list partial templates, at very least. They can likely be similar/the same tempates.
- [x] Member list and team member list parent templates use the same logic for pending notifications
- [ ] #228

**Comment by agjohnson** [comment]
Thought I'd share an update on some of the filters here. I'm relying on django-filter for many of the views, and using this UX/UI as a way to consolidate views -- for example, instead of incorporating a list of projects in the team detail UI I will instead link to a filtered list of projects in another UI.

However, there are a few hurdles I've found with django-filter which caused some headaches:

- The set up for the filter classes happens at the class level.
- Filters fields aren't intended for a use case like showing a list of teams associated with an organization. By default, model filter fields show *all teams associated with any organization*.
- The filterset have several methods for tuning the queryset, but none of them work for our case due to one of the above reasons.

The end solution is ugly in comparison but it is indeed working at least.

The byproduct of this is that I finally found the pattern I wanted in order to surface a search dropdown list for projects/teams/orgs. Currently, these dropdowns use an API call and separate front end code. With the work I did here, we'll be able to do this all from the filter instead.

Next up, we keep talking about the lack of tests for the filters, and I definitely felt this trying to get the filters working correctly. However, I'm not sure how effective I'll be here so I might punt on this and continue with the dashboard changes for now.

**Comment by agjohnson** [comment]
Filter changes are here: https://github.com/readthedocs/readthedocs.org/pull/10847

This is what the filters look like currently:

[Screencast from 2023-10-18 19-59-55.webm](https://github.com/readthedocs/readthedocs.org/assets/1140183/65140193-c47c-4eb9-80dc-2d26464b7d35)

**Comment by agjohnson** [comment]
The last of the views that I have been chipping away at are the missing team admin/listing views. I ended up reworking an earlier attempt and making this into a subview of sorts, similar to how the project admin dashboard is a subview of the project dashboard. This mostly makes me want to move all of these views into the organization admin now though, I think that is the correct place for these types of views and there is not much value in duplicating views like _organization project listing_ and _team project list_ when there are filters on the organization project listing.

![image](https://github.com/readthedocs/ext-theme/assets/1140183/809c4c6c-db46-4722-850d-4ee6185f2a28)
